# Site settings
title:          Culture Quantified
description:    "A look at the algorithms that surround and define modern American culture."
url:            "https://culture-quantified.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Sumeet Bansal
  url:          https://sumeet-bansal.github.io
  email:        s3bansal@ucsd.edu

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
